User.create({username: "admin", email: "admin@admin.com", password: "admin-password"})
User.create({username: "test-2", email: "test-2@email.com", password: "test-2-password"})
User.create({username: "test-3", email: "test-3@email.com", password: "test-3-password"})
User.create({username: "test-4", email: "test-4@email.com", password: "test-4-password"})
User.create({username: "test-5", email: "test-5@email.com", password: "test-5-password"})

t1 = Time.new(1993, 2, 24, 12, 0, 0, "+09:00").strftime("%Y-%m-%d %H:%M:%S")
t2 = Time.new(2007, 1, 25, 07, 0, 8, "+09:00").strftime("%Y-%m-%d %H:%M:%S")
t3 = Time.new(2007, 1, 25, 11, 1, 6, "+09:00").strftime("%Y-%m-%d %H:%M:%S")
t4 = Time.new(2002, 9, 16, 12, 0, 0, "+09:00").strftime("%Y-%m-%d %H:%M:%S")
t5 = Time.new(2018, 11, 15, 02, 4, 3, "+09:00").strftime("%Y-%m-%d %H:%M:%S")

Post.create({content: "Here is another piece to work with.", date_posted: t2, user_id: 2})
Post.create({content: "Hopefully this will help.", date_posted: t3, user_id: 3})
Post.create({content: "Can I order this correctly?", date_posted: t4, user_id: 4})
Post.create({content: "Yes, I can!", date_posted: t5, user_id: 5})
Post.create({content: "This is some sample content!", date_posted: t1, user_id: 6})

Genre.create({name: "Pop"})
Genre.create({name: "Blues"})
Genre.create({name: "Jazz"})
Genre.create({name: "Rock"})
Genre.create({name: "R&B"})

t6 = Time.new(1998, 4, 24, 10, 3, 6, "+09:00").strftime("%Y-%m-%d %H:%M:%S")
t7 = Time.new(2007, 7, 13, 07, 0, 8, "+09:00").strftime("%Y-%m-%d %H:%M:%S")
t8 = Time.new(2007, 3, 25, 11, 1, 6, "+09:00").strftime("%Y-%m-%d %H:%M:%S")
t9 = Time.new(2002, 8, 18, 12, 0, 0, "+09:00").strftime("%Y-%m-%d %H:%M:%S")
t10 = Time.new(2018, 12, 15, 02, 4, 3, "+09:00").strftime("%Y-%m-%d %H:%M:%S")

Song.create({name: "I'm Yours", release_date: t7, user_id: 2})
Song.create({name: "Love Story", release_date: t8, user_id: 3})
Song.create({name: "Happier", release_date: t9, user_id: 4})
Song.create({name: "Bohemian Rhapsody", release_date: t10, user_id: 5})
Song.create({name: "Your Song", release_date: t6, user_id: 6})

Album.create({name: "Album-2", release_date: t7, user_id: 2})
Album.create({name: "Album-3", release_date: t8, user_id: 3})
Album.create({name: "Album-4", release_date: t9, user_id: 4})
Album.create({name: "Album-5", release_date: t10, user_id: 5})
Album.create({name: "Album-1", release_date: t6, user_id: 6})